openapi: 3.0.0
info:
  title: User Service API
  description: API for user registration, login, profile management, password reset, email verification, and OAuth updates
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Local User Server

tags:
  - name: "🔵 USER SERVICE - Authentication"
    description: "User Service: Registration, login, and authentication endpoints"
  - name: "🔵 USER SERVICE - Profile"
    description: "User Service: Profile management and updates"
  - name: "🔵 USER SERVICE - Security"
    description: "User Service: Password management and email verification"
  - name: "🔵 USER SERVICE - OAuth"
    description: "User Service: OAuth integration and updates"

paths:
  /api/v1/user/register:
    post:
      summary: Register a new user
      tags:
        - "🔵 USER SERVICE - Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Rajan Kumar
                email:
                  type: string
                  format: email
                  example: raorajan9576@gmail.com
                role:
                  type: string
                  enum: [developer, project-owner, admin]
                  default: developer # 👈 default role
                  example: developer
                domains:
                  type: string
                  example: "web, ai-ml"
                experience:
                  type: string
                  example: "3 years"
                availability:
                  type: string
                  enum: [full-time, part-time, freelance]
                  default: full-time
                  example: full-time
                password:
                  type: string
                  format: password
                  example: 123123
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Bad request

  /api/v1/user/login:
    post:
      summary: Login a user
      description: Authenticates user and returns JWT token stored in HTTP-only cookie for security
      tags:
        - "🔵 USER SERVICE - Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [email, password, role]
              properties:
                email:
                  type: string
                  format: email
                  example: raorajan9576@gmail.com
                role:
                  type: string
                  enum: [developer, project-owner, admin]
                  default: developer # 👈 default role
                  example: developer
                password:
                  type: string
                  example: 123123
      responses:
        "200":
          description: Login successful - JWT token stored in HTTP-only cookie
          headers:
            Set-Cookie:
              description: JWT token stored in HTTP-only cookie
              schema:
                type: string
                example: "token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Strict"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Login successful"
                  user:
                    $ref: "#/components/schemas/User"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Invalid email or password"

  /api/v1/user/profile:
    get:
      summary: Get user profile
      tags:
        - "🔵 USER SERVICE - Profile"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized
        "404":
          description: User not found
        "500":
          description: Internal server error

    put:
      summary: Update user profile
      description: Update editable profile fields (does not allow email, password, ID, or system fields)
      tags:
        - "🔵 USER SERVICE - Profile"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: Profile updated successfully
        "400":
          description: Invalid request data
        "401":
          description: Unauthorized
        "404":
          description: User not found
        "500":
          description: Internal server error

    delete:
      summary: Delete user profile
      tags:
        - "🔵 USER SERVICE - Profile"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User deleted successfully
        "401":
          description: Unauthorized
        "404":
          description: User not found
        "500":
          description: Internal server error

  /api/v1/user/verify-email:
    get:
      summary: Verify email using token
      tags:
        - "🔵 USER SERVICE - Security"
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Email verified
        "400":
          description: Invalid or expired token

  /api/v1/user/verify-email/{id}:
    get:
      summary: Verify email using user ID (fallback)
      tags:
        - "🔵 USER SERVICE - Security"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Email verified
        "404":
          description: User not found

  /api/v1/user/forgot-password:
    post:
      summary: Send password reset email
      tags:
        - "🔵 USER SERVICE - Security"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [email]
              properties:
                email:
                  type: string
      responses:
        "200":
          description: Reset email sent
        "404":
          description: User not found

  /api/v1/user/reset-password/{token}:
    put:
      summary: Reset password using token
      tags:
        - "🔵 USER SERVICE - Security"
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [newPassword]
              properties:
                newPassword:
                  type: string
      responses:
        "200":
          description: Password reset successful
        "400":
          description: Invalid or expired token

  /api/v1/user/change-password:
    put:
      summary: Change password (logged-in user)
      tags:
        - "🔵 USER SERVICE - Security"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [currentPassword, newPassword]
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        "200":
          description: Password changed
        "401":
          description: Invalid current password

  /api/v1/user/oauth:
    put:
      summary: Update OAuth details
      tags:
        - "🔵 USER SERVICE - OAuth"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [oauthProvider, oauthId]
              properties:
                oauthProvider:
                  type: string
                oauthId:
                  type: string
      responses:
        "200":
          description: OAuth details updated

  /api/v1/user/logout:
    post:
      summary: Logout the currently logged-in user
      description: Invalidates the user's session and clears the JWT token from HTTP-only cookie. No client-side token removal needed.
      tags:
        - "🔵 USER SERVICE - Authentication"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logout successful - JWT token cleared from HTTP-only cookie
          headers:
            Set-Cookie:
              description: JWT token cleared from HTTP-only cookie
              schema:
                type: string
                example: "token=; HttpOnly; Secure; SameSite=Strict; Max-Age=0"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Logged out successfully"
        "401":
          description: Unauthorized – missing or invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Unauthorized"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Logout failed"
                  error:
                    type: string
                    example: "Error message"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        uuid:
          type: string
        name:
          type: string
        email:
          type: string
        bio:
          type: string
        avatarUrl:
          type: string
        domainPreferences:
          type: string
        skills:
          type: object
        experience:
          type: string
        location:
          type: string
        availability:
          type: string
        resumeUrl:
          type: string
        xp:
          type: integer
        badges:
          type: array
          items:
            type: string
        level:
          type: integer
        githubUrl:
          type: string
        linkedinUrl:
          type: string
        stackoverflowUrl:
          type: string
        portfolioScore:
          type: integer
        isEmailVerified:
          type: boolean
        notificationPrefs:
          type: object
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    UserUpdate:
      type: object
      properties:
        name:
          type: string
          example: Rajan Kumar
        bio:
          type: string
          example: Full Stack Developer
        avatarUrl:
          type: string
          example: https://example.com/avatar.png
        domainPreferences:
          type: string
          example: web, ai-ml
        skills:
          type: object
          example: { "javascript": "advanced", "react": "intermediate" }
        experience:
          type: string
          example: 3 years
        location:
          type: string
          example: Nagpur, Maharashtra
        availability:
          type: string
          example: full-time
        resumeUrl:
          type: string
          example: https://example.com/resume.pdf
        xp:
          type: integer
          example: 0
        badges:
          type: array
          items:
            type: string
          example: ["Top Performer"]
        level:
          type: integer
          example: 1
        githubUrl:
          type: string
          example: https://github.com/raobaba
        linkedinUrl:
          type: string
          example: https://www.linkedin.com/in/kumar-rajan
        stackoverflowUrl:
          type: string
          example: https://stackoverflow.com/users/123456
        portfolioScore:
          type: integer
          example: 0
        notificationPrefs:
          type: object
          example: { "email": true, "sms": false }
      required: []
