openapi: 3.0.0
info:
  title: User Service API
  description: API for user registration, login, profile management, password reset, email verification, and OAuth updates
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Local User Server

paths:
  /api/v1/users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered successfully
        "409":
          description: User already exists

  /api/v1/users/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /api/v1/users/profile:
    get:
      summary: Get user profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile returned
        "404":
          description: User not found

    put:
      summary: Update user profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Profile updated

    delete:
      summary: Delete user profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User deleted

  /api/v1/users/verify-email:
    get:
      summary: Verify email using token
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Email verified
        "400":
          description: Invalid or expired token

  /api/v1/users/verify-email/{id}:
    get:
      summary: Verify email using user ID (fallback)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Email verified
        "404":
          description: User not found

  /api/v1/users/forgot-password:
    post:
      summary: Send password reset email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [email]
              properties:
                email:
                  type: string
      responses:
        "200":
          description: Reset email sent
        "404":
          description: User not found

  /api/v1/users/reset-password/{token}:
    put:
      summary: Reset password using token
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [newPassword]
              properties:
                newPassword:
                  type: string
      responses:
        "200":
          description: Password reset successful
        "400":
          description: Invalid or expired token

  /api/v1/users/change-password:
    put:
      summary: Change password (logged-in user)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [currentPassword, newPassword]
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        "200":
          description: Password changed
        "401":
          description: Invalid current password

  /api/v1/users/oauth:
    put:
      summary: Update OAuth details
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [oauthProvider, oauthId]
              properties:
                oauthProvider:
                  type: string
                oauthId:
                  type: string
      responses:
        "200":
          description: OAuth details updated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        uuid:
          type: string
        name:
          type: string
        email:
          type: string
        bio:
          type: string
        avatarUrl:
          type: string
        domainPreferences:
          type: string
        skills:
          type: object
        experience:
          type: string
        location:
          type: string
        availability:
          type: string
        resumeUrl:
          type: string
        xp:
          type: integer
        badges:
          type: array
          items:
            type: string
        level:
          type: integer
        githubUrl:
          type: string
        linkedinUrl:
          type: string
        stackoverflowUrl:
          type: string
        portfolioScore:
          type: integer
        isEmailVerified:
          type: boolean
        notificationPrefs:
          type: object
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
