CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"password" varchar(255),
	"oauth_provider" text,
	"oauth_id" text,
	"bio" text,
	"avatar_url" text,
	"domain_preferences" text,
	"skills" json,
	"experience" text,
	"location" text,
	"availability" text,
	"resume_url" text,
	"xp" integer DEFAULT 0,
	"badges" json DEFAULT '[]'::json,
	"level" integer DEFAULT 1,
	"github_url" text,
	"linkedin_url" text,
	"stackoverflow_url" text,
	"portfolio_url" text,
	"portfolio_score" integer,
	"is_email_verified" boolean DEFAULT false,
	"reset_password_token" text,
	"reset_password_expire" timestamp,
	"notification_prefs" json DEFAULT '{}'::json,
	"role" "role" DEFAULT 'developer' NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_uuid_unique" UNIQUE("uuid"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
